# See https://blog.christophvoigt.com/setting-up-hugo-with-github-pages/
language: go

branches:
  only:
    - develop

env:
  global:
    secure: "H1RfnAEc5SYCRavKczGddXK/AdjgRPydYJ+Ubl5iYzaoBpUPCRXiJqxn1XdnuG05iK+B9IasYjgGS13kpFAb/0JXumfBjk+AfhOA3OsBFBwDLpucn2m3BdcEpxq6jM9Q7gdKDk6xvCJ2Nrv3SMAvrIIfjzu9CXVWAg1jSe+UFlHM+8YQjW41iRRyUiMUEbCYJjI4KOrFU7d5h5+MTMcdZBP0DLK1Cit8NyMzPtF1Zrhum+EHLfZS/Ai/EwOkEKJmmWqvt8hFDMwHg0ggiV0C7WlU/745oPypim+m1jhGxwz1JETFmTELyEO9OCVxexJ5omtkniaue5Gra5Hq9L1V0tKYLLeeFZqWc0H7WW0H4P7fUeJ8WAKjy6uySbU5ia/gm5kHamV+MS5HwuTSYSQUFdwxyo0P3jxyzR+drIzqMnRB4gGwlSAoGpnoDsMRe4a7esEnJ+qs672Hf6/9apZnFz/ds+Bhd6x9jjzl3N6LQopYpcmXIG+Zkry4Tku401btasUrGjjT3k3CYvKcSuvUeyYxvPeHO8W3h4qu4oWVUB179A+Na1u+dByOuSwQcy1W21nvTJApaAtxQpfVImH0cQfDBZGfPt1luv9/HFd+6JiDt34GD1CMh9KfLdZ66JcwDKXB9/e/FcmwJ0eZwEeye+gZ9+XRGNyYpXQ2EVN3omI="

install:
  - go get -v github.com/spf13/hugo
  - rm -rf public || exit 0
script:
  - hugo
  - bash deploy.sh

notifications:
  slack:
    secure: I2O/QHAIMg0mfYKX9K9DFP4aLg0Ih8xK9pFKpR2HfSNC6XVfwkvcabPKCIhjX22yBt0q2LsA7X7KYjvPRSBm/xU1HnKsueNc7/0GX64NWG84ABHGKKmglwf01lqg9bPSpt642XjhZ/ogHQ9OYW0duN8lx3k/iCZmCa14NVb/Wsih+JQ5QI6B6yR+jFmFvAhQFhnxRJHeKxOHb8dRL5I/2oFj/2VcXokULfkU13UVTnD4YGWBh0wR0RkQU9O9wZh9t0/Ou/kq76sHnntnjmQ9vyq6+NdiPP6WCX1mZVzsmwpVLKCsQBtLV3GkY85MgISuvvQ0HbZI6td6Sbi4ia8ao1vhRH77GDJqzqPEXNtk5Ff3Rud0sAclmCWDEMk4AbESm3XVwI/35osgdvO+cVGfdI6oOCe4ndgD6VFj0vNLZFDFnL0AJ4CxCCVF9beG0hf+jUJjJF0ZYqhHdXdgT618LYvi5nAPO1BHxw9y1tkfKl/WbX0a3THpv2QU050qUXQRe5rgiPAp6uO72OmpVr/TuKdKsVerBLwLzuRaiKb4hFaq1abeIPWZJ/luETKnPIwD/1TLOrvWi46xQjMXy1N9x/FmsNIVCzzVf8NxXO5lL1+Xz8kwo6cZfJ9g2cQHCgHZ/avKtsPpo/DiJ8fRokR8tjOEIpTIJLk9ZjmiEoi9yww=
